decent-chat/decent

api.js
site/js/index.js

Please note: this makes message dates be stored as numbers (the output of `Date.now`) rather than ISO-formatted strings. @heyitsmeuralex, you will probably have to update #5. (Just remove `Date.parse` - see this PR's changes in `site/js/index.js`.)

Add API to fetch old messages in a channel

---

site/styles.css

Fixes #39.
There's not currently a particular case where any text is affected by this, but this gets rid of the potential for accidentally black-on-black text.

Fix text sometimes being displayed as black

---

api.js

Towards #17.
Send a POST request to `/api/pin-message` including your session ID and the message you want to pin to add a message to its channel's pinned message list. Only administrators can pin messages.
Send a GET request to `/api/channel/:channelID` to get the list of pinned messages (which is not returned through `/api/channel-list`):
This doesn't do anything on the client-side.

Add pinned message API

---

api.js
site/js/SessionActor.js
site/js/Socket.js

Includes #62! Merge that one before this.
Fixes #63.
This adds a simple online/offline status system. Any serialized user will include whether the user is online or not (in the `online` field). In order to do this, I added a `sessionID` field to socket data; this is filled in by the client's `pong data` event, which is sent in response to the server's `ping for data` event. (`ping for data` is sent as soon as the socket connects, and on the ping interval.) In order to see if a user is online or not, the API simply checks for any socket whose session ID belongs to that user.

Add online offline status

---

api.js

Fixes #9.
`/api/create-channel {"name":"Haha invalid name!!!", "sessionID":...}` -> `{"error":"name invalid"}`

Validate channel names on backend

---

api.js
site/js/MessagesActor.js
site/styles.css

Fixes #73.
Edited messages still display "(Edited)" beside the content (now with the edit date as the title text), but you cannot click to view old revisions (which are no longer stored).

Remove message revisions API; update client for this

---

api.js

Fixes #85.
Before, the channel wasn't even being serialized before being responded - yikes!
(Branch title gore.. :shipit:)

Respond with channel ID in create-channel

---

api.js
site/js/ChannelsActor.js

Fixes #97.
Adds a new channel for deleting APIs: `POST /api/delete-channel {channelID, sessionID}`
And a corresponding socket event: `deleted channel {channelID}`
Adds a quick change to the client to reload the channel list when a channel is deleted, though it should be noted that it, if the deleted channel was selected, a different channel won't automatically be selected.

Delete channel API

---

api.js
site/js/MessagesActor.js

Fixes #94. Towards #66.
This implements a new API for deleting messages:
`POST /api/delete-message {messageID, sessionID}`
A small client implementation is also included. It's basically only a reference for now, since the client is in the process of being rewritten (#77). Also, it does not follow the spec as described in #66 (i.e. no "message action" dropdown); rather, it replaces the error message that shows up when a message is edited and a zero-length input is entered.
Note that the client implementation does not give a way to delete someone else's message, but this can be tested through the console:
```js
fetch('/api/delete-message', {
method: 'post',
headers: {'Content-Type': 'application/json'},
body: JSON.stringify({messageID: '...', sessionID: actors.session.sessionID})
})
``` …

Delete message API

---

api.js
site/js/ChannelsActor.js

Fixes #90. Towards #66.
This emits a socket event to all clients `renamed channel { channelID, newName }` when a channel is renamed.
There's also a small reference implementation for the client code to handle this event.

Emit socket event on channel rename

---

.gitignore
api.js
index.js
package.json
site/quick-upload.html
yarn.lock

Issue/PR 100 :tada:
Fixes #99. Towards #18.
`POST upload-file?sessionID=.. <FormData {image: file}>`. Responds with `{success: true, path}` if successful, where `path` is the string you'd enter into your location bar (or an `<img src>`) to load the image.
Uses [Multer](https://github.com/expressjs/multer) to upload files. Files are saved according to the format `__dirname/uploads/<shortid>/<basename of original name>.<extension based on MIME type>`. Files can only be uploaded by admins (as this is mainly for custom emotes), and cannot be greater than 10MB in size (in case an admin accidentally selects the wrong file; obviously small emote icons should never be this big). Only MIME types `image/png`, `image/gif`, and `image/jpeg` are uploaded. (By the way: this means *animated* custom …

Add image upload API

---

README.md

Otherwise, `oof` won't be cloned. Git submodules aren't unflawed :package:

Update README to include --recursive in git clone

---

site/index.js

Fixes #118.
This also scrolls to the bottom of a channel when you select it, because loading a channel calls `appendMessage` (a bunch of times). It works even if you're not scrolled to the bottom when you click on a channel, because the channel element is cleared, thus resetting `el.scrollHeight - el.offsetHeight` to zero; so `wasScrolledToBottom` evaluates to true.

Scroll to bottom when appending new messages

---

api.js

Before:
```js
for (let i = 0; i < 100; i++) {
console.log(generalValidNameRegex.test('john'))
}
```
```
true
false
true
false
true
false
true
false
...
```
After:
```js
for (let i = 0; i < 100; i++) {
cosnole.log(isNameValid('john'))
}
```
```
true
true
true
true
true
true
true
true
...
```
See MDN on [RegExp.prototype.test](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#Description). Particularly:
> `test()` called multiple times on the same global regular expression instance will advance past the previous match.
Surprise, surprise, `.test` has side effects.. JavaScript was a mistake :upside_down_face:

Fix alternating name validity tests failing

---

api.js
package.json
site/js/app.css
site/js/app.js
site/js/components/account-settings.css
site/js/components/account-settings.js
site/js/components/message-group.js
site/js/components/messages.js
site/js/components/sidebar.css
site/js/components/sidebar.js
site/js/util/api.js
site/js/util/modal.css
yarn.lock

Resolves #101 :tada:  
This PR merges into `componentize`, **not** master, to help with merge conflicts. It therefore blocks it.
Uses libravatar, and stores email addresses on the server. You get a default retro avatar based on the md5 hash of your user ID:
And you can use the account settings page (accessed by clicking your username in the session info area in the sidebar) at `/servers/:host/account-settings` to edit the email address associated with your account.
Note that "Change password" just runs `alert('not implemented')`.
Any further messages from you will take your avatar URL with them (`msg.authorAvatarURL`):
User objects now have a string `authorAvatarURL` field. Likewise, message objects have `authorAvatarURL`, set at the time they are created. Note: in the database these …

Add account settings page/api endpoint and user profile pictures (avatars)

---

settings.js

Was caused by a missing 'async' keyword. Surprised this went unnoticed for so long!

Fix server properties not persisting

---

api.js

The actual path `/api/` (and `/api`) weren't having the appropriate response headers set. This PR fixes that.
(It also adds a missing period in that endpoint's "message" field, which I think should be there.)

Fix headers not being set on '/api/'

---

api.js
docs/api.md
site/src/app.css
site/src/app.js
site/src/components/account-settings.css
site/src/components/account-settings.js
site/src/components/message-group.js
site/src/components/sidebar.js
site/src/util/date.js

This PR contains two Big Things: automatic deletion of old sessions (fixes #43) and manual deletion of sessions. It also contains a few changes to the API and related documentation.
**Automatic deletion of old sessions** fixes #43 by pruning sessions that are at least 30 days old every five minutes and on server startup.
**Manual deletion of sessions** is a new feature which lets any user delete any sessions logged into their account. It looks like this:
You (and only you) can view and delete sessions from your account settings page.
Relevant API documentation can be found in commit a1396a7447fcb15e082e6ac221709309f2c9b823.
This is blocked by PR #141; I intend to update `/session/:sessionID` to return session objects, but I can't change it right now because #141 already changes the …

Session deletion

---

site/src/components/account-settings.js

Before, the list would be fetched *every* time the route changed, even if the new route wasn't the account settings page. Oops!

Only fetch session list upon account settings re-render

---

site/src/app.js
site/src/components/sidebar.js

This fixes session authorization being borked by making the `sessionAuthorized` state into a "magic" property. It will *always* equal true when the server does not require authorization, regardless of whatever it was actually set to. (This is stored internally on the state as `_sessionAuthorized`; see the diff for how it works.)
I'm not certain, but I'm fairly sure this fixes emotes not being loaded immediately, which in turn makes messages actually be rendered (rather than not be rendered because emotes are yet to be fetched).

Fix session authorization code, for real

---

site/src/app.js

This will gracefully not do anything if the server requires authorization (because [this](https://github.com/decent-chat/decent/blob/4088b9a7d4f2ae1d0b60caf45494de4a3de46280/site/src/components/srv-settings/emotes.js#L15-L16)); if the server *doesn't* require authorization, emotes will immediately be loaded, which will permit messages to be rendered.

Immediately try to fetch emotes when switching to a server

---

site/src/app.js
site/src/util/ws.js

..so that WS doesn't need to call `api`. Also, this makes WS independent of Decent (so it could be used in other programs, if wanted).
This gets rid of the "Host string provided, not state object" warning.

Pass state.secure directly to WS

---

api.js
docs/api.md
site/src/components/message-group.css
site/src/components/messages.js

Fixes #148; fixes #162. Unblocks #17 and #93.
This makes a few (non-breaking) changes to the API (besides fixing some old, broken behavior).
This implements scroll-forwards (loading more recent messages when scrolling down, when newer messages are not loaded) *and* jumping to a message by its ID. There's no exposed UI for that yet, but you can (and should) test it with `choo.emit('messages.jumptomessage', '(messageID)')`.
PS: Firefox (on my machine, anyways) behaves really weirdly, when scrolling backwards *or* forwards? It doesn't actually scroll back to the previously oldest message group after loading the older messages (in the case of loading older messages). Then it immediately loads *more* old messages. That's a cycle, so it keeps loading old messages until all old messages are …

Scrollforward / Jump to old message

---

api.js
docs/api.md
site/src/app.js
site/src/components/messages.js
site/src/components/sidebar.js

Renames a bunch of WebSocket events:
* `ping for data` -> `pingdata`
* `pong data` -> `pongdata`
* `received chat message` -> `message/new`
* `edited chat message` -> `message/edit`
* `created new channel` -> `channel/new`
* `renamed channel` -> `channel/rename`
* `deleted channel` -> `channel/delete`
Updates the client to deal with these changes, as well.
Also fixes the code which handled "deleted channel"; this used to error, but now actually removes the channel from the channel list (with no error).

Rename websocket events; fix channel-delete handler of client

---

api.js
docs/api.md

Enables authentication with *any route* via:
* sessionID in post body
* sessionID in query string
* X-Session-ID in request headers
Before, some routes would expect sessionID to be in the post body, some in the query string, etc. This makes them not care. Documentation has been updated to match.
No frontend changes have been made, but it should be trivial to evict all `?sessionID` and `{ sessionID }` declarations in api.js calls. Just using X-Session-ID is definitely much easier.
---
@towerofnix I'd recommend some extra testing for this particular PR than usual. I don't normally work on the backend all that much, and this is an API-wide change. I may have overlooked something.
@TheInitializer this may make weecent's code simpler or something, so you might want to take a look once/if this …

Centralize route authentication

---

site/src/app.css

This adds a margin to the bottom child element of `.page`s, so that you can scroll that distance ahead. This only really has an effect when the browser window is fairly short; before, elements like the table in the account settings page would appear right at the bottom of the screen (so the bottom of the table touched the bottom of the page).

Fix missing padding at the bottom of .page elements

---

packages/cli/bin/decent.js

`/usr/bin/env` is always available, whereas `/usr/bin/node` may not be (e.g. if `nvm` is used). This PR fixes that.
(Labeling this because the CLI not working on systems that don't have `/usr/bin/node` is a bug!)

Use 'usr/bin/env node' for CLI shebang line

---

packages/server/api.js

/api/channel-list was broken, for example.

Fix 'invalid session ID' error with runIfVarExists

---

packages/client/src/app.js

Obviously `data` should be the data (e.g. `{ message: {} }`), but instead it was the timestamp at which the event was gotten. This fixes that. (This is a very very important fix because without it, the client doesn't react to *any* WS events correctly.)

Fix "data" arg of ws.* events being the event timestamp

---

packages/server/api.js

Fixes #191.
It turns out we weren't checking for authorization properly, so the "else" block wasn't being activated. And there was a typo in `runIfCondition` preventing "else" blocks from working, anyways; that's fixed as well.
@heyitsmeuralex I marked this semver: patch, but I'm not actually experienced with semantic versioning; is that right?

Respond full user list if authorization is disabled

---

docs/api.md
packages/client/src/components/sidebar.js
packages/client/src/components/srv-settings/emotes.js
packages/client/src/util/api.js
packages/server/api.js
packages/server/errors.js

Fixes #196 by changing the API as described there. This is obviously a breaking change (the client is updated in this PR as well).
> This first pass focuses on two things:
>
> 1. Destroy any usage of `{success: true}`.
> 2. Make sure all returned values are an object, with specific details (e.g. user list) responded in separate properties (e.g. `"users": []`) and not stored on the top-level returned object itself.
>
> ---
>
> This part finishes up the clean-up, adding proper errors. Docs need to be updated.

Clean up API

---

packages/cli/bin/decent.js
packages/client/src/app.js
packages/client/src/components/account-settings.js
packages/client/src/components/message-editor.js
packages/client/src/components/messages.js
packages/client/src/components/sidebar.js
packages/client/src/components/srv-settings/authorized-users.js
packages/client/src/components/srv-settings/emotes.js
packages/client/src/util/api.js
packages/client/src/util/modal.js
packages/server/api.js

The client used to be dead. Now it isn't.
This changes old endpoints in the client's code to new endpoints. I probably missed some, but this is a good start.
Some other things I changed:
* You'll automatically be logged in after registering.
* You'll automatically get kicked out of the account settings page if you log out while in it (e.g. by deleting your current session, or just clicking the "logout" button).
* Holding alt while pressing the up/down arrow keys switches to the channel above or below the current one in the channel list. This loops - if you're on the top channel and press up, it'll move to the bottom one (and vice versa). (Fixes #13.)
* Viewing a channel immediately focuses the message textarea (if you're logged in).
* Pressing escape cancels the active modal. (Fixes #12.) …

Fix client

---

docs/api.md
packages/client/src/app.js
packages/client/src/components/srv-settings/authorized-users.js
packages/client/src/components/user-list.js
packages/client/src/util/api.js
packages/server/api.js

None of these are tracked, but this commit fixes authorization errors on both the client and the server.
It's a major/breaking change for the server (see below), and a patch change for the client (since it just fixes bugs).
* Fixes properties in general not being fetched correctly (on the client). `state.secure`, `state.serverRequiresAuthorization`, and `state.authorizationMessage` now actually work.
* Fixes the user list causing several errors that prevent messages from being loaded and such (mainly because it assumed a non-authorized server).
* Changes PATCH /api/settings to POST /api/settings (this is the breaking change, see below).
Important commit message:
>For some reason, no matter absolutely what, Express wasn't handling PATCH /api/settings. I have no idea why. Changing the …

Fix authorization-related errors

---

packages/client/src/components/message-editor.js

Doing so on an interval was making it impossible to focus on anything else. This was an issue for me when I tried to create a second channel and couldn't type its name.
Obviously this is still a hack and will be changed later anyway, but it's nice to also have it fixed in the short-term.

Only focus message input once

---

docs/api.md
packages/client/src/components/user-list.js
packages/server/api.js

Fixes #217.
The code and docs here are pretty self-descriptive, but the tl;dr is that there are two new events - `user/new` and `user/gone` - called when a user is created/authorized and deleted/deauthorized, respectively. These events are reflected in the user list sidebar.

Add user register/leave events, and make user list respond to these

---

packages/client/package.json

Fixes build errors related to tinyify/uglify that kept on occurring, namely on mercury - the https://meta.decent.chat production server!! - and, sometimes, my local machine.
Oh, and I removed `dependency-check` and the `__kb` display after builds too because we don't really need them and nobody likes bloat.
CC @TheInitializer - this removes the `rm dist/*;` part of the build step so it should start working on Windows now, please test.

Use uglify-es instead of tinyify

---

packages/client/src/components/sidebar.js

Adds the necessary code to assume the state of `channel.unreadMessages` based on message WS events. Also calls `mark-as-read` when switching to a channel.

Handle unread notifications on client-side

---

docs/api.md
packages/client/src/app.js
packages/server/api.js

This publishes `/api/settings` (so that it doesn't require authorization) and updates the client to fetch the authorization message from the server's settings instead of its properties (which never contained the message in the first place).

Fetch authorization message on client properly

---

packages/client/src/components/preferences/appearance.js

Changes flair styling (in the dark theme) from this:
...to this:

Improve flair styling in dark theme

---

packages/client/src/components/srv-settings/emotes.js

Firefox does *not* like it when you try to `createElement('br/')`. This is admittedly a problem that should be fixed in choo, but it's easy enough to quickly change here.

Change <br> to <br/>

---

packages/client/src/app.js

Fixes #245.
Two problems were happening here:
* We were checking for `user` changing, instead of `id`. This means that we would respond `pongdata {sessionID: {username: 'florrie'}}`, etc, instead of `pongdata {sessionID: '1234'}`.
* We were checking if the new `value` was different from `target.id`... but of course, this is never true, since we'd just ran `Reflect.set(target, 'id')`! We now keep track of the old value and compare the new value to that.

Fix automatic pongdata so it actually does its thing

---

packages/client/src/components/messages.js

This PR makes `unreadMessageCount` be set to zero in the sidebar after scrolling to the end of a channel. There are certainly edge-cases - what to do when viewing a channel with so few messages that it is impossible to scroll comes to mind - but those really are edge-cases. This is a quick fix for typical cases (channels with lots of messages).

Very simple half-fix for unread messages

---

packages/client/src/app.js
packages/client/src/components/sidebar-left.js
packages/client/src/components/sidebar-right.js

Fixes a few client errors that aren't being tracked. I get that we're working on the preact client, but these are helpful while still developing with the non-preact client.
* No more error when you first open the page (i.e. when the route does not have a `host` parameter). Now the client resets to a "not in server" state, instead of trying to fetch `http://undefined/api/properties`.
* No more error when your user doesn't show up in the user list, for whatever reason.
* No more error when the client automatically restores a session ID, but that session has been deleted. It treats that as you being logged out now.

Avoid a few miscellaneous client errors

---

docs/api.md
packages/client/src/app.js
packages/client/src/util/api.js
packages/server/api.js
packages/server/settings.js
packages/server/test/api-misc.js

This generally updates settings to follow the 1.0.0 specification.
* Changes `POST /api/settings` to `PATCH /api/settings`.
* Implements `server-settings/updated { settings }`.
* Removes `GET /api/properties`.
* Adds `useSecureProtocol` field to `/api`. (Also adds tests for this.)
* Makes minor changes to the client to handle these.

Implement 1.0.0-spec settings

---

docs/api.md
packages/server/api.js
packages/server/common.js
packages/server/serialize.js
packages/server/test/api-messages.js
packages/server/test/common.js
packages/server/test/serialize.js

* Updated message datetime keys as per spec (more consistent with the rest of the API):
* `message.date` -> `message.dateCreated`
* `message.editDate` -> `message.dateEdited`
* Updates tests to reflect
* Fix #297 
- We now store dates to millisecond-level accuracy, however the serialize functions floor the value before they are outputted by the API.
+ This fixes some tests.
- We may want to get the spec to specify whether these dates should always be integers (what we're doing now) or may be floats.
- Note that currently the API specifies "number" as the type. This is ambiguous, and we should probably use 'integer' and 'float' across the entire spec if applicable.

1.0.0 impl: various datetime fixes

---

LICENSE.txt
README.md
packages/cli/README.md
packages/cli/bin/decent.js
packages/cli/package.json
packages/client/README.md
packages/client/package.json
packages/server/README.md

Note that the MPL recommends we include the following header in all source files, but we don't have to and nor do we, provided LICENSE.txt is somewhere. Also updated the `license` command in the cli.
```js
/* This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.            */
```
Resolves #293.

Use the MPL
