LICENSE.txt, index.js, package-lock.json, package.json
=> Add GPL 3.0 LICENSE.TXT file and license command

index.js, yarn.lock
=> Allow specification of port to run on

api.js
For the username creation dialog, which will constantly fetch `/api/username-available/(usernameInput.value)` while typing and show a string "available" or "not available".
=> Add username-available API

site/js/SessionActor.js
=> Registration modal: error on unavailable username before asking for passsword

site/js/MessagesActor.js, site/styles.css
=> Message groups

package.json
Fixes #22.
Note the "homepage" field, which was automatically generated by `npm init` - I guess we're supposed to make a readme!
=> Fill in package.json

api.js, index.js, package.json, site/index.html, site/js/Actor.js, site/js/ChannelsActor.js, site/js/MessagesActor.js, site/js/SessionActor.js, site/js/Socket.js, site/js/api.js, site/js/index.js, site/styles.css, yarn.lock
=> Decentralize client & stop using socket.io

site/js/ChannelsActor.js, site/js/MessagesActor.js, site/js/SessionActor.js
(Includes #45!!)
Adjusts autoscrolling - on message receive - more lenient. Some of us were having issues with it, and this seems to fix it 🎉
=> More lenient autoscrolling

site/js/MessagesActor.js
=> Format mentions only if the user actually exists

site/js/SessionActor.js
lol rebasing branches of branches
=> Remove repeated addEventListener calls

site/js/MessagesActor.js, site/styles.css
Visiting `+server.com#the-default-aka-first-channel` would load messages there twice.
=> Fix channelref bug

site/img/caret-down.svg, site/index.html, site/js/SessionActor.js, site/styles.css
=> Add server list

site/js/SessionActor.js
"[]" is fatal! This should fix deserealization of LocalStorage.sessionIDs even if it's malformed.
=> Fix localStorage again

site/index.html
=> Allow MouseTrap events to fire inside #chat-input

api.js
Fixes #55. Online/offline isn't in this yet, but once that's implemented into the database and added to `sanitize.user` it automatically will appear here.
=> Add user-list API

api.js
Towards #66. Implements "rename channels - backend".
`POST /api/rename-channel {channelID, name, sessionID}`
=> Add rename-channel and simplify name-validation code

site/js/MessagesActor.js, site/styles.css
=> Fix code blocks using multiple <code> elements

api.js
=> Refactor channelShort to channelBrief

api.js
Fixes #87. No need to keep any of this code now! :boom:
=> Remove dead channelID code

api.js, site/js/MessagesActor.js
Fixes #35 (again). Removes some old, dead code.
=> Remove dead OpenPGP code

site/quick-upload.html
Removes an old, unused line of code. This doesn't fix any particular issue.
=> Remove debug line in quick-upload.html

site/tags/message-group.tag
I can't believe you were developing this with the API *that* old :tada:
=> Update Riot client to work with new API

.gitignore, .travis.yml, package.json, riot.config.js, site/index.html, yarn.lock
Fixes #107. Building on #77. This *does not* include source maps because I couldn't figure out how to get them to work, and I'm quite certain we aren't going to be using Riot in the future anyways.
I don't know how to test Travis. Maybe pushing .travis.yml will do something. :woman_shrugging:
=> Travis deploy and Riot build script

.travis.yml
Continuing off of #108, towards #107.
=> Fix on-branch in gh-pages

README.md, index.js, package.json
Fixes #78 🎈 
Most of the README is stolen from @PullJosh's satirical comment on #78. Thanks 📦 
<h6>@towerofnix, these changes assume that the name of this repo will change to 'decent,' so please do that when this gets merged. Would also recommend changing the repo description to `:balloon: The decentralized chat system that's absolutely okay`, too!</h6>
=> Rename to Decent

api.js
Towards #31 and #122.
These changes are based on an old commit that was never merged. (Note that you can specify both the "before" and "after" properties, and it'll still work.)
=> Add ?before and ?after query parameters to latest-messages API

api.js, site/js/components/message-editor.css, site/js/components/message-editor.js, site/js/components/message-group.css, site/js/components/message-group.js, site/js/components/messages.js, site/js/util/api.js
This PR merges into componentize, not master.
* `![]()` - you can now include images in your markdown ✔️ ⬇️ 
* pasting inside the message editor will upload an image (you don't have to be admin anymore! this should be a configuration option per-server, I guess) and send a message including it :tada: 📋
=> Add image uploading

README.md
Documents @TheInitializer's weechat client for Decent servers 🎉
=> Document Weecent (weechat-decent)

docs/api.md
As discussed. Relates to #143.
=> Move documentation into docs/ rather than GH wiki

site/src/util/date.js
=> Fix month formatting in date stringify util

packages/client/package.json
Watch was outputting to dist/decent.js, not dist/bundle.js!!
=> @decent/client: clear dist/* and fix watch script

docs/api.md
This just fixes a couple of spelling mistakes.
=> Fix Some Spelling Mistakes

packages/server/api.js, packages/server/index.js, packages/server/package.json
Cherrypicked from the `nanocomponents` branch.
=> Fix CORS for X-Session-ID

packages/cli/bin/decent.js
=> Fix "set" CLI command causing a reference error

packages/client/src/components/sidebar.js
=> Fix always seeming authorized

docs/api.md
Ping @TheInitializer; you were the one to realise this.
=> Document /api/[de]authorize-user

packages/client/src/app.js
=> Fix broken and add missing 404s

packages/client/css/pages/authorized-users.css
=> Remove hacks to fix authorized users table centering

packages/client/css/generic/message.css, packages/client/src/components/message-group.js
Conditions for bigmoji:
* Message only contains emotes
* Max 16 emotes in a single message
=> Add bigmoji

packages/client/css/app.css, packages/client/css/generic/avatar.css, packages/client/css/generic/input.css, packages/client/css/generic/message-group.css, packages/client/css/pages/account-settings.css, packages/client/css/specific/user-list.css, packages/client/src/app.js, packages/client/src/components/account-settings.js, packages/client/src/components/message-group.js, packages/client/src/components/preferences/looks.js, packages/client/src/components/sidebar.js, packages/client/src/components/srv-settings/authorized-users.js, packages/client/src/components/user-list.js
* Adds preferences section to sidebar
* Adds _Looks_ preferences page, with a single option - circular avatars via CSS variables - towards #185
* DRYified some `app.js` code
* Moved the previously-`.AccountSettings-input`-specific horizontal input style to `Input --horizontal`
=> Add preferences

docs/api.md, packages/client/src/components/sidebar.js, packages/server/api.js
Displays hostname, channel, and unread message count. After we make the server name editable in the client we should update this (and the server dropdown) to use the defined name instead.
=> Add channel/update event; set document.title based on state

packages/client/src/components/message-group.js, packages/client/src/util/mrk.js
(foreign references = channelrefs, eg. `#channel`, `+hostname.com#channel`)
=> Fix mrk parsing of foreign references & allow 3 bigmoji max

packages/client/css/app.css, packages/client/css/generic/input.css, packages/client/css/generic/page.css, packages/client/css/generic/table.css, packages/client/css/pages/account-settings.css, packages/client/css/specific/modal.css, packages/client/css/specific/session-info.css, packages/client/src/components/account-settings.js, packages/client/src/components/preferences/appearance.js, packages/client/src/components/srv-settings/emotes.js
=> Add dark theme

packages/server/api.js
Oops.
(Currently live on meta.decent.chat.)
=> Fix crash when attempting to change email

packages/client/src/util/ws.js
I tested identical changes on the test server and it worked :upside_down_face:
=> Fix WebSockets not opening securely

docs/api.md
**Work in progress.** @heyitsmeuralex I've still got to make a few changes to this (e.g. "Permissions int" is still lying around).
=> Redo 1.0.0 permission spec

packages/client/css/app.css, packages/client/css/generic/avatar.css, packages/client/css/generic/button.css, packages/client/css/generic/input.css, packages/client/css/generic/message-editor.css, packages/client/css/generic/message.css, packages/client/css/generic/page.css, packages/client/css/generic/table.css, packages/client/css/pages/account-settings.css, packages/client/css/specific/server-dropdown.css, packages/client/css/specific/sidebar.css, packages/client/img/send.svg, packages/client/src/components/account-settings.js, packages/client/src/components/message-group.js, packages/client/src/components/preferences/appearance.js, packages/client/src/components/sidebar-left.js, packages/client/src/components/sidebar-right.js
Made a bunch of small changes to polish up the design.
The only thing that's iffy is the send button. It looks nicer, but is weird when the message gets long. In an ideal world, the textarea would auto-expand while typing so that it doesn't need to scroll, and if the height got maxed out (somewhere around ~400px tall?) the send button would move over to the left a little to make room for the scroll bar.
=> Design tweaks

packages/client/src/util/mrk.js
Untested, and relies on my PR in mrk being merged.
So, like, don't merge yet :-)
Fixes #282
=> Prevent XSS in images

packages/client/src/util/mrk.js
This PR is ***untested***; and I'm afraid I won't be able to get a local copy up due to memory restrictions (I might try to do so at some point, but I'd prefer someone else with more disk space do so)
**Note**: *Please observe that this PR is for the `xss` branch, not the `master`. Is that a bad idea?*
=> Fix XSS for Decent-flavoured links in Markdown

packages/server/api.js
Rather than complaining and crashing, just complain really loudly.
=> Fix unhandled websockets error due to Chrome bug
